<DownloadViewItem>:
    size_hint_y: None
    height: '100dp'
    padding: 5
    radius: 10
    MDFloatLayout:
        size_hint_x: None
        width: root.height
        CommonIcon:
            id: icon
            icon: root.icon
            font_size: "42sp"
            pos_hint: {"center_x": .5, "center_y": .5}

    MDBoxLayout:
        orientation: "vertical"
        spacing: 2
        MDBoxLayout:
            id: title_cont
            CommonLabel:
                id: title

        MDBoxLayout:
            id: progress_cont_parent
            size_hint_y: .001
            MDLabel:
                id: status
                adaptive_width: True

        MDBoxLayout:
            #
            id: btns
            size_hint_y: .8


<DownloadViewItemProgressContainer>:
    MDProgressBar:
        id: progressbar
        value: 0
        pos_hint: {"center_x": .5, "center_y": .5}


<DownloadViewItemButton>:
    size_hint_x: .5
    CommonLabel:
        halign: "left"
        id: label

<DownloadViewItemMini>:
    orientation: "vertical"
    MDBoxLayout:
        DownloadViewItemProgressContainer:
            id: progress_cont
            view_model: root.view_model
            size_hint_y: None
            height: 4
            pos_hint: {"center_x": .5, "center_y": .5}
        MDBoxLayout:
            adaptive_width: True
            CommonIconButton:
                icon: "pause"
                on_release: root.pause()
                disabled: True
                icon_size: 14
                size: 20, 20

            CommonIconButton:
                icon: "close"
                on_release: root.cancel()
                icon_size: 14
                size: 20, 20

    MDBoxLayout:
        CommonLabel:
            id: info
            shorten: True
            small: True